version: "3.8"
services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - ./src/adaptor/postgres/schema.sql:/docker-entrypoint-initdb.d/init.sql
